#!/usr/bin/env python3

#The purpose of this file is to take a script and show a list of results in order for someone to review to search the script manually after for any resulting concerning words generated by the script.

import re, requests, sys;

#Press ctrl+Fn+End to get past all the bad words.
words="""

















































god
jesus
christ
lord
jee
gee
golly
gosh
heaven
goodness
sake
oh my
oh, my
holy
cow
devil
deuce
damn
damm
dang
darn
drat
hell
heck
screw
whore
bloody
bastard
blast
counfounded
shit
crap
fuck
stupid
dumb
idiot
lame
butt
ass
curse
bitch
stink
clumsy
clumsiness
lousy
ugly
dumm
kopf
mongrel
flea
bitten
clown
bite
kiss
bug
gay
homo
fag
blazes
blazing
evil
piss
puss
cum
cunt
beer
wine
alcohol
vodka
gin
champagne
cocktail
strip
drinking
drunk
sloshed
queer
cheat
adultery
murder
kill
sex
intercourse
bed
naked
smoke
cigar
cigarette
drug
inject
marijuana
cannabis
opioid
jeepers
caffeine
patch
nicotine
hate
brilliant
spirits
magic
witch
hag
divination
astrolog
OMG
erotic
bourbon
brandy
fool
geek
nerd
dork
egghead
doof
goof
""".strip()









goodwords="""
love
charity
faith
kind
happy
bless
nice
play
polite
believe
power
precious
priceless
effective
efficient
amiable
cordial
sentimental
church
admir
philanthrop
hope
glory
sweet
happiness
happier
happiest
modest
virtue
virtuous
patience
temperance
courage
brave
sincere
sincerity
empathy
empathetic
compassion
sympathy
sympathetic
humility
humble
mercy
merciful
mature
meaningful
miracle
mirth
namaste
noble
moderation
generous
generosity
forgive
forgiveness
honor
wisdom
justice
wise
loyal
loyalty
persevere
perseverance
assert
human
trust
self-control
selfless
attentive
joy
integrity
gentle
lady
diligence
diligent
care
caring
clean
commit
confidence
consideration
considerate
assurance
beaut
pretty
gorgeous
fortitude
family
angel
awesome
bliss
benefi
brilliance
calm
peace
tranquil
cheer
champion
celebrat
cute
creative
cool
radical
divine
dazzling
delight
earnest
ecstatic
elegant
enchanting
appealing
exquisite
fabulous
fantastic
favorable
friend
fun
fortunate
grace
genius
smile
hug
handsome
heal
harmony
harmonious
true
truth
honest
intelligent
nurtur
nutritio
perfect
poise
prepar
principl
resilient
producti
safe
secure
skill
adept
apt
super
surprise
terrific
thorough
thrive
thriving
unwavering
upbeat
upstanding
value
valuable
vibrant
victory
victorious
vitality
welcome
gratitude
thank
wonderful
wondrous
zeal
alacrity
accepted
acceptance
accomodat
accura
accomplish
ador
revere
reverent
reverence
affable
adroit
curious
delicious
fancy
frugal
thrift
glad
heart
jubilant
jolly
free
liberty
life
lovable

""".strip()

script=""

foulwords=words.split("\n")
goodwords=goodwords.split("\n")

story="""

This is a test!

Hello, my name is Sam.

Check this out.

"""






















class LangCheck:
    def __init__(self, words, script):
        self.results={};
        self.evaluate(words, script);
    def handle_expletive_regex(self, match):
        text=match.group();
        if text not in self.results:
            self.results[text]=1;
        else:
            self.results[text]+=1;
        return text;
    def evaluate(self, words, script):
        script=script.lower();
        for x in words:
            re.sub("\w*"+x+r"\w*", self.handle_expletive_regex, script);
        tfl=[]; #temporary foul language list (unsorted)
        for k,v in self.results.items():
            tfl.append(k+" "+str(v));
        tfl.sort();
        print("\n".join(tfl));
        return self.results;

#l=LangCheck(foulwords, story);
#webscript=requests.get("https://www.gutenberg.org/cache/epub/514/pg514.txt").text;

if __name__=="__main__":
    if len(sys.argv)==2:
        webscript=requests.get(sys.argv[1]).text;
        l=LangCheck(foulwords, webscript);
        #print("\n\n\n\n\n")
        #l2=LangCheck(goodwords, webscript);
